### ISSUE TITLE
Get mouse to detect direction

### ISSUE THREAD

**Issue by andyyvo** [andyyvo/avofolio#2]
## Idea
Get the app to figure out which direction the cursor is moving.

## Description
We want to utilize the `on:mousemove MouseEvent` to tell the custom cursor component which direction it is going in.

## To-dos
- [x] Log the direction
- [x] Diffuse log throttling by delaying detection
- [x] Change something about the cursor based on the direction
    - [x] Get classname to change
